name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t rondinelisaad/opac:${VERSION} \
            -t rondinelisaad/opac:latest \
            .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: scielo/opac:${VERSION}
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Generate SBOM (CycloneDX)
        run: |
          trivy image \
            --format cyclonedx \
            --output sbom-${VERSION}.json \
            rondinelisaad/opac:${VERSION}

      - name: Push image
        run: |
          docker push rondinelisaad/opac:${VERSION}
          docker push rondinelisaad/opac:latest
